### ISSUE TITLE
Default buildout README needs to be updated

### ISSUE THREAD

**Issue by cdw9** [sixfeetup/bobtemplates.sixfeetup#6]
It contains some old information, and make sure the quick start info is up to date.

**Comment by cdw9** [comment]
also switch to using Markdown for the file. Note this will need to be updated in the setup.py

**Comment by cdw9** [comment]
Let's also include release information

**Comment by abosio** [comment]
> Let's also include release information

@cdw9 What release information were you thinking of?

**Comment by cdw9** [comment]
That was based on the idea of specific site release information be in the README instead of the wiki
